use serde_json::Value;

pub fn resolve_secret_token(v: &Value, gateway_dir: &std::path::Path) -> Option<String> {
    let tok = &v["channels"]["telegram"]["botToken"];
    if tok.get("source")?.as_str()? != "file" {
        return None;
    }
    let id = tok.get("id")?.as_str()?;
    let raw = std::fs::read_to_string(gateway_dir.join("secrets.json")).ok()?;
    let secrets: Value = serde_json::from_str(&raw).ok()?;
    let s = secrets.pointer(id)?.as_str()?;
    if s.is_empty() {
        None
    } else {
        Some(s.to_string())
    }
}

pub struct Migration {
    pub toml: String,
    pub notes: Vec<String>,
}

fn known_provider(kind: &str) -> bool {
    matches!(kind, "anthropic" | "openai" | "openrouter" | "ollama")
}

fn compat_base_url(kind: &str) -> Option<&'static str> {
    match kind {
        "nvidia" => Some("https://integrate.api.nvidia.com/v1"),
        "groq" => Some("https://api.groq.com/openai/v1"),
        "mistral" => Some("https://api.mistral.ai/v1"),
        "deepseek" => Some("https://api.deepseek.com/v1"),
        _ => None,
    }
}

fn toml_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

fn toml_list(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| toml_str(s)).collect();
    format!("[{}]", inner.join(", "))
}

fn map_model(id: &str, notes: &mut Vec<String>) -> (String, String, String) {
    let Some((prefix, rest)) = id.split_once('/') else {
        notes.push(format!(
            "model '{id}' has no provider prefix; kept as-is under provider \"anthropic\": adjust if wrong"
        ));
        return ("anthropic".into(), id.to_string(), String::new());
    };
    if known_provider(prefix) {
        return (prefix.to_string(), rest.to_string(), String::new());
    }
    if let Some(url) = compat_base_url(prefix) {
        notes.push(format!(
            "provider '{prefix}' mapped to an OpenAI-compatible endpoint ({url})"
        ));
        return (prefix.to_string(), rest.to_string(), url.to_string());
    }
    notes.push(format!(
        "provider '{prefix}' is not built in; set provider.base_url to its OpenAI-compatible endpoint"
    ));
    (prefix.to_string(), rest.to_string(), String::new())
}

fn str_list(v: &Value) -> Vec<String> {
    v.as_array()
        .map(|a| {
            a.iter()
                .filter_map(|x| match x {
                    Value::String(s) => Some(s.clone()),
                    Value::Number(n) => Some(n.to_string()),
                    _ => None,
                })
                .collect()
        })
        .unwrap_or_default()
}

pub fn from_gateway(v: &Value) -> Migration {
    let mut notes = Vec::new();
    let mut out = String::from("# Generated by `phoenix migrate` from an AI gateway config.\n");

    let primary = v["agents"]["defaults"]["model"]["primary"]
        .as_str()
        .unwrap_or("");
    let (provider, model, base_url) = if primary.is_empty() {
        notes.push("no agents.defaults.model.primary found; provider left at defaults".into());
        (String::new(), String::new(), String::new())
    } else {
        map_model(primary, &mut notes)
    };
    out.push_str("\n[provider]\n");
    if !provider.is_empty() {
        out.push_str(&format!("kind = {}\n", toml_str(&provider)));
        out.push_str(&format!("model = {}\n", toml_str(&model)));
    }
    if !base_url.is_empty() {
        out.push_str(&format!("base_url = {}\n", toml_str(&base_url)));
    }
    out.push_str("# api_key comes from the PHOENIX_API_KEY env var; never stored here.\n");

    let vars = crate::config::provider_key_vars(&provider);
    let found = vars
        .iter()
        .find(|v| std::env::var(v).map(|s| !s.is_empty()).unwrap_or(false));
    if let Some(var) = found {
        notes.push(format!(
            "{var} is already set in this environment; phoenix will use it \
automatically (PHOENIX_API_KEY overrides it)"
        ));
    } else {
        notes.push("export PHOENIX_API_KEY with the API key for the provider above".into());
    }

    let fallbacks = str_list(&v["agents"]["defaults"]["model"]["fallbacks"]);
    let mut kept = Vec::new();
    for fb in &fallbacks {
        match fb.split_once('/') {
            Some((p, rest)) if p == provider => kept.push(rest.to_string()),
            _ => notes.push(format!(
                "fallback '{fb}' is on a different provider; phoenix fallbacks stay within one provider, skipped"
            )),
        }
    }
    if !kept.is_empty() {
        out.push_str(&format!("fallbacks = {}\n", toml_list(&kept)));
    }

    out.push_str("\n[agent]\nsessions = true\n");

    let workspace = v["agents"]["defaults"]["workspace"]
        .as_str()
        .unwrap_or("")
        .to_string();
    let ask = v["tools"]["exec"]["ask"].as_str().unwrap_or("off");
    let ask_on = ask != "off";
    if !workspace.is_empty() || ask_on {
        out.push_str("\n[security]\n");
        if !workspace.is_empty() {
            out.push_str(&format!("workspace = {}\n", toml_str(&workspace)));
        }
        if ask_on {
            out.push_str("approvals = true\n");
            notes.push(format!(
                "gateway exec ask was {ask:?}; carried over as security.approvals = true: \
serve chats queue shell commands until you send /approve. Delete the line to run directly"
            ));
        }
    }
    if !ask_on {
        notes.push(
            "exec approvals stay off (phoenix default): serve chats run shell commands \
directly. Set security.approvals = true to queue them for /approve"
                .into(),
        );
    }

    let tg = &v["channels"]["telegram"];
    if tg.is_object() {
        let allowed = str_list(&tg["allowFrom"]);
        out.push_str("\n[telegram]\n");
        match tg["botToken"].as_str() {
            Some(tok) if !tok.is_empty() => {
                out.push_str(&format!("token = {}\n", toml_str(tok)));
                notes.push(
                    "telegram bot token copied from plaintext config; keep config.toml at mode 600 or move it to PHOENIX_TELEGRAM_TOKEN"
                        .into(),
                );
            }
            _ => {
                out.push_str("# token comes from PHOENIX_TELEGRAM_TOKEN; the gateway kept it as a secret reference.\n");
                notes.push("export PHOENIX_TELEGRAM_TOKEN with your Telegram bot token".into());
            }
        }
        out.push_str(&format!("allowed_chat_ids = {}\n", toml_list(&allowed)));
        if allowed.is_empty() {
            notes.push(
                "telegram allowFrom was empty; phoenix fails closed until allowed_chat_ids is set"
                    .into(),
            );
        }
    }

    let wa = &v["channels"]["whatsapp"];
    if wa.is_object() {
        let allowed: Vec<String> = str_list(&wa["allowFrom"])
            .iter()
            .map(|n| n.trim_start_matches('+').to_string())
            .collect();
        out.push_str("\n[whatsapp]\n");
        out.push_str("# token comes from PHOENIX_WHATSAPP_TOKEN.\n");
        out.push_str("# phone_id / verify_token come from your Meta app; see README.\n");
        out.push_str(&format!("allowed_numbers = {}\n", toml_list(&allowed)));
        notes.push(
            "the gateway's WhatsApp uses QR pairing; phoenix uses the Business Cloud API. \
Create a Meta app, then set PHOENIX_WHATSAPP_TOKEN, whatsapp.phone_id, and whatsapp.verify_token"
                .into(),
        );
    }

    Migration { toml: out, notes }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn resolves_file_backed_secret_token() {
        let dir = std::env::temp_dir().join(format!("phx-migrate-sec-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("secrets.json"),
            r#"{"channels":{"telegram":{"botToken":"123:secret"}}}"#,
        )
        .unwrap();
        let v = json!({"channels": {"telegram": {"botToken": {
            "source": "file", "provider": "filemain",
            "id": "/channels/telegram/botToken"}}}});
        assert_eq!(
            resolve_secret_token(&v, &dir),
            Some("123:secret".to_string())
        );

        let v2 = json!({"channels": {"telegram": {"botToken": {"source": "env"}}}});
        assert_eq!(resolve_secret_token(&v2, &dir), None);
        let v3 = json!({"channels": {"telegram": {"botToken": "plain"}}});
        assert_eq!(resolve_secret_token(&v3, &dir), None);

        let v4 = v.clone();
        assert_eq!(resolve_secret_token(&v4, &dir.join("nope")), None);
    }

    fn sample() -> Value {
        json!({
            "agents": {"defaults": {
                "model": {"primary": "anthropic/claude-sonnet-4-6",
                           "fallbacks": ["anthropic/claude-haiku-4-5", "openrouter/meta/llama-3.3-70b"]},
                "workspace": "~/work"
            }},
            "channels": {
                "telegram": {"enabled": true, "botToken": {"source": "env"},
                              "allowFrom": ["1868769425"]},
                "whatsapp": {"allowFrom": ["+4915551234567"]}
            }
        })
    }

    #[test]
    fn maps_provider_and_model() {
        let m = from_gateway(&sample());
        assert!(m.toml.contains("kind = \"anthropic\""));
        assert!(m.toml.contains("model = \"claude-sonnet-4-6\""));
        assert!(m.toml.contains("fallbacks = [\"claude-haiku-4-5\"]"));
        assert!(m
            .notes
            .iter()
            .any(|n| n.contains("openrouter/meta/llama-3.3-70b")));
    }

    #[test]
    fn secret_refs_never_copied() {
        let m = from_gateway(&sample());
        assert!(!m.toml.contains("source"));
        assert!(m.toml.contains("PHOENIX_TELEGRAM_TOKEN"));
        assert!(m.toml.contains("allowed_chat_ids = [\"1868769425\"]"));
    }

    #[test]
    fn plaintext_token_carries_with_warning() {
        let mut v = sample();
        v["channels"]["telegram"]["botToken"] = json!("123:abc");
        let m = from_gateway(&v);
        assert!(m.toml.contains("token = \"123:abc\""));
        assert!(m.notes.iter().any(|n| n.contains("mode 600")));
    }

    #[test]
    fn whatsapp_allowlist_strips_plus() {
        let m = from_gateway(&sample());
        assert!(m.toml.contains("allowed_numbers = [\"4915551234567\"]"));
        assert!(m.notes.iter().any(|n| n.contains("Cloud API")));
    }

    #[test]
    fn nvidia_maps_to_compat_endpoint() {
        let v = json!({"agents": {"defaults": {"model": {"primary": "nvidia/meta/llama-3.1-70b-instruct"}}}});
        let m = from_gateway(&v);
        assert!(m.toml.contains("kind = \"nvidia\""));
        assert!(m.toml.contains("model = \"meta/llama-3.1-70b-instruct\""));
        assert!(m
            .toml
            .contains("base_url = \"https://integrate.api.nvidia.com/v1\""));
    }

    #[test]
    fn unknown_provider_gets_base_url_note() {
        let v = json!({"agents": {"defaults": {"model": {"primary": "acme/foo-1"}}}});
        let m = from_gateway(&v);
        assert!(m.notes.iter().any(|n| n.contains("base_url")));
    }

    #[test]
    fn empty_config_still_renders() {
        let m = from_gateway(&json!({}));
        assert!(m.toml.contains("[provider]"));
        assert!(m.notes.iter().any(|n| n.contains("primary")));
    }

    #[test]
    fn workspace_and_sessions_carry() {
        let m = from_gateway(&sample());
        assert!(m.toml.contains("sessions = true"));
        assert!(m.toml.contains("workspace = \"~/work\""));
    }

    #[test]
    fn exec_ask_on_maps_to_approvals_true() {
        for ask in ["on", "always"] {
            let mut v = sample();
            v["tools"] = json!({"exec": {"ask": ask}});
            let m = from_gateway(&v);
            assert!(m.toml.contains("approvals = true"), "ask={ask}");
            assert!(m.notes.iter().any(|n| n.contains("/approve")));
        }
    }

    #[test]
    fn exec_ask_off_or_missing_maps_to_nothing() {
        let mut v = sample();
        v["tools"] = json!({"exec": {"ask": "off"}});
        for cfg in [&v, &sample()] {
            let m = from_gateway(cfg);
            assert!(!m.toml.contains("approvals"));
            assert!(m
                .notes
                .iter()
                .any(|n| n.contains("approvals stay off (phoenix default)")));
        }
    }
}
